services:
  postgres:
    container_name: postgres_container
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  keycloak:
    container_name: keycloak_container
    ports: 
      - 8400:8080
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - postgres

volumes:
  postgres_data: